# Generated by Django 6.0.4 on 2026-04-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0004_alter_employe_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="email",
        ),
    ]
