# Generated by Django 6.0.4 on 2026-04-20 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0005_remove_employe_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conge",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="conge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="conge",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conges",
                to="employe.employe",
            ),
        ),
    ]
