# Generated by Django 6.0.4 on 2026-04-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employe", "0003_employe_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("heure_entree", models.TimeField(blank=True, null=True)),
                ("heure_sortie", models.TimeField(blank=True, null=True)),
                ("retard_minutes", models.IntegerField(default=0)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
            options={
                "unique_together": {("employe", "date")},
            },
        ),
    ]
