# Generated by Django 6.0.4 on 2026-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="presence",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="presence",
            name="date_modification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presence",
            name="duree_travail_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="presence",
            name="est_modifie_manuellement",
            field=models.BooleanField(default=False),
        ),
    ]
