# Generated by Django 6.0.4 on 2026-04-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0004_alter_employe_user"),
        ("presence", "0002_alter_presence_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("IN", "Entrée"), ("OUT", "Sortie")], max_length=10
                    ),
                ),
                ("heure", models.TimeField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Presence",
        ),
    ]
