# Generated by Django 6.0.4 on 2026-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0003_presencelog_delete_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="presencelog",
            name="est_modifie_manuellement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="presencelog",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="presencelog",
            name="heure",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="presencelog",
            name="type",
            field=models.CharField(max_length=10),
        ),
    ]
