# Generated by Django 6.0.4 on 2026-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0004_presencelog_est_modifie_manuellement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presencelog",
            name="type",
            field=models.CharField(max_length=3),
        ),
    ]
