# Generated by Django 6.0.4 on 2026-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0005_alter_presencelog_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presencelog",
            name="type",
            field=models.CharField(
                choices=[("IN", "Entrée"), ("OUT", "Sortie")], max_length=3
            ),
        ),
    ]
